# Generated by Django 3.2 on 2021-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='content_type',
            field=models.CharField(choices=[('question', 'Question'), ('advise', 'Advise'), ('achievement', 'Achievement'), ('success_key', 'Success Key'), ('contact', 'Contact'), ('goal', 'Goal'), ('other', 'Other'), ('tips', 'Tips')], max_length=200),
        ),
    ]
