# Generated by Django 3.2 on 2021-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_auto_20210626_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
