# Generated by Django 3.2 on 2021-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_alter_interview_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='interview Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/%y')),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='video',
        ),
        migrations.AlterField(
            model_name='article',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
