# Generated by Django 3.2 on 2021-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_auto_20210626_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='interview',
        ),
        migrations.AddField(
            model_name='article',
            name='interview',
            field=models.ManyToManyField(to='articleapp.Interview'),
        ),
    ]
