# Generated by Django 3.2 on 2021-06-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_auto_20210626_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
