# Generated by Django 3.2 on 2021-06-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_interview_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='articleapp.MediaArticle'),
        ),
        migrations.AddField(
            model_name='mediaarticle',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
