# Generated by Django 3.2 on 2021-06-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_auto_20210627_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='media',
            field=models.ManyToManyField(to='articleapp.MediaArticle'),
        ),
    ]
