# Generated by Django 3.2 on 2021-06-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0008_alter_interview_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='content_type',
            field=models.CharField(choices=[('question', 'Question'), ('inspirations', 'Inspirations'), ('success_key', 'Success Key'), ('ideas', 'Ideas'), ('stories', 'stories'), ('achievement', 'Achievement'), ('influencers', 'Influencers'), ('contact', 'Contact'), ('goal', 'Goal')], max_length=200),
        ),
    ]
