# Generated by Django 3.2 on 2021-06-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0009_alter_interview_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='content',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='media',
        ),
        migrations.RemoveField(
            model_name='article',
            name='interview',
        ),
        migrations.AddField(
            model_name='article',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articleapp.interview'),
        ),
        migrations.CreateModel(
            name='InterViewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('inspirations', 'Inspirations'), ('success_key', 'Success Key'), ('ideas', 'Ideas'), ('stories', 'stories'), ('achievement', 'Achievement'), ('influencers', 'Influencers'), ('contact', 'Contact'), ('goal', 'Goal')], max_length=200)),
                ('media', models.ManyToManyField(to='articleapp.MediaArticle')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='contents',
            field=models.ManyToManyField(to='articleapp.InterViewContent'),
        ),
    ]
