# Generated by Django 3.2 on 2021-06-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0010_auto_20210627_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='about',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
