# Generated by Django 3.2 on 2021-06-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0011_auto_20210627_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(default='')),
                ('content_format', models.CharField(choices=[('plain text', 'Plain Text'), ('list text', 'List Text')], default='plain text', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='interviewcontent',
            name='content_type',
            field=models.CharField(choices=[('question', 'Question'), ('inspirations', 'Inspirations'), ('success_key', 'Success Key'), ('ideas', 'Ideas'), ('stories', 'stories'), ('achievement', 'Achievement'), ('influencers', 'Influencers'), ('contact', 'Contact'), ('goal', 'Goal')], default='question', max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleapp.content'),
        ),
    ]
