# Generated by Django 3.2 on 2021-06-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0012_auto_20210627_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcontent',
            name='content',
        ),
        migrations.AddField(
            model_name='interviewcontent',
            name='content',
            field=models.ManyToManyField(to='articleapp.Content'),
        ),
    ]
