# Generated by Django 3.2 on 2021-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0013_auto_20210627_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarticle',
            name='gender',
            field=models.CharField(choices=[('male', 'Male Avatar'), ('female', 'Female Avatar')], default='male', max_length=400),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='image',
            field=models.ImageField(upload_to='interview Image'),
        ),
    ]
