# Generated by Django 3.2 on 2021-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0014_auto_20210627_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaarticle',
            name='image',
            field=models.ImageField(default='profile/male_avatar.svg', upload_to='interview Image'),
        ),
    ]
