# Generated by Django 3.2 on 2021-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0015_alter_mediaarticle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaarticle',
            name='gender',
        ),
        migrations.AddField(
            model_name='interviewcontent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male Avatar'), ('female', 'Female Avatar')], default='male', max_length=400),
        ),
    ]
