# Generated by Django 3.2 on 2021-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0016_auto_20210627_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcontent',
            name='content_type',
            field=models.CharField(choices=[('question', 'Question'), ('inspiration', 'Inspiration'), ('success_key', 'Success Key'), ('idea', 'Idea'), ('story', 'story'), ('achievement', 'Achievement'), ('influencer', 'Influencer'), ('contact', 'Contact'), ('goal', 'Goal')], default='question', max_length=200),
        ),
    ]
