# Generated by Django 3.2 on 2021-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0017_alter_interviewcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcontent',
            name='content_type',
            field=models.CharField(choices=[('question', 'Question'), ('inspiration', 'Inspiration'), ('success_key', 'Success Key'), ('story', 'story'), ('idea', 'Idea'), ('achievement', 'Achievement'), ('influencer', 'Influencer'), ('contact', 'Contact'), ('goal', 'Goal')], default='question', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaarticle',
            name='image',
            field=models.ImageField(upload_to='interview_image'),
        ),
    ]
