# Generated by Django 3.2 on 2021-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0018_auto_20210627_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcontent',
            name='content',
        ),
        migrations.AddField(
            model_name='interviewcontent',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
