# Generated by Django 3.2 on 2021-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0021_auto_20210629_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='inst',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ld',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='twt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interviewcontent',
            name='content_type',
            field=models.CharField(choices=[('question answer', 'Question Answer'), ('list question answer', 'List Question Answer'), ('inspiration', 'Inspiration'), ('success_key', 'Success Key'), ('story', 'story'), ('idea', 'Idea'), ('achievement', 'Achievement'), ('influencer', 'Influencer'), ('contact', 'Contact'), ('goal', 'Goal')], default='question', max_length=200),
        ),
    ]
