# Generated by Django 3.2 on 2021-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0022_auto_20210629_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='inst',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='ld',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='twt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
